In [ ]:
import pandas as pd
import plotly.express as px

In [ ]:
df=pd.read_csv('/content/crimes.xlsx - crimes.csv.csv')

In [ ]:
df

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA NAME,Crm Cd Desc,Vict Age,Vict Sex,Vict Descent,Weapon Desc,Status Desc,LOCATION
0,221412410,2022-06-15,2020-11-12,1700,Pacific,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),0,NaN,NaN,NaN,Invest Cont,13600 MARINA POINT DR
1,220314085,2022-07-22,2020-05-12,1110,Southwest,THEFT OF IDENTITY,27,F,B,NaN,Invest Cont,2500 S SYCAMORE AV
2,222013040,2022-08-06,2020-06-04,1620,Olympic,THEFT OF IDENTITY,60,M,H,NaN,Invest Cont,3300 SAN MARINO ST
3,220614831,2022-08-18,2020-08-17,1200,Hollywood,THEFT OF IDENTITY,28,M,H,NaN,Invest Cont,1900 TRANSIENT
4,231207725,2023-02-27,2020-01-27,635,77th Street,THEFT OF IDENTITY,37,M,H,NaN,Invest Cont,6200 4TH AV
...,...,...,...,...,...,...,...,...,...,...,...,...
247983,231510379,2023-05-29,2023-05-25,1100,N Hollywood,"BUNCO, GRAND THEFT",25,M,W,NaN,Invest Cont,5300 DENNY AV
247984,231604807,2023-01-27,2023-01-26,1800,Foothill,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",23,M,H,NaN,Invest Cont,12500 BRANFORD ST
247985,231606525,2023-03-22,2023-03-22,1000,Foothill,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",25,F,H,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,12800 FILMORE ST
247986,231210064,2023-04-12,2023-04-12,1630,77th Street,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",29,M,B,UNKNOWN WEAPON/OTHER WEAPON,Invest Cont,6100 S VERMONT AV
247987,230906458,2023-03-05,2023-03-05,900,Van Nuys,VANDALISM - MISDEAMEANOR ($399 OR UNDER),53,F,H,NaN,Invest Cont,14500 HARTLAND ST

In [ ]:
df.shape

(247988, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247988 entries, 0 to 247987
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   DR_NO         247988 non-null  int64
 1   Date Rptd     247988 non-null  object
 2   DATE OCC      247988 non-null  object
 3   TIME OCC      247988 non-null  int64
 4   AREA NAME     247988 non-null  object
 5   Crm Cd Desc   247988 non-null  object
 6   Vict Age      247988 non-null  int64
 7   Vict Sex      215740 non-null  object
 8   Vict Descent  215739 non-null  object
 9   Weapon Desc   80087 non-null   object
 10  Status Desc   247988 non-null  object
 11  LOCATION      247988 non-null  object
dtypes: int64(3), object(9)
memory usage: 22.7+ MB

# Data Cleaning

In [ ]:
df.isna().sum()

DR_NO                0
Date Rptd            0
DATE OCC             0
TIME OCC             0
AREA NAME            0
Crm Cd Desc          0
Vict Age             0
Vict Sex         32248
Vict Descent     32249
Weapon Desc     167901
Status Desc          0
LOCATION             0
dtype: int64

In [ ]:
df['Weapon Desc'].fillna('Unknown',inplace=True)
df['Vict Sex'].fillna('Unknown',inplace=True)
df['Vict Descent'].fillna('Unknown',inplace=True)

/tmp/ipykernel_3686/4002171115.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipykernel_3686/4002171115.py:2: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipykernel_3686/4002171115.py:3: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [ ]:
df.duplicated().sum()

np.int64(0)

# 1- Peak Crime Hour

In [ ]:
df['Hour']=df['TIME OCC']//100

In [ ]:
# حساب عدد الجرائم في كل ساعة
hour_counts=df['Hour'].value_counts().sort_index()
# استخراج ساعة الذروة
peak_crime_hour=int(hour_counts.idxmax())
print(f'The peak crime hour is: {peak_crime_hour}')
fig1=px.line(x=hour_counts.index,y=hour_counts.values,title='Crimes by Hour of Day',labels={'x':'Hour','y':'Number of Crimes'},markers=True)
fig1.show()

The peak crime hour is: 12

In [ ]:
### Bonus ###
# 1. تحويل عمود التاريخ إلى datetime (تأكد من مطابقة صيغة التاريخ في ملفك)
df['Date_Cleaned'] = pd.to_datetime(df['DATE OCC'])

# 2. استخراج اسم يوم الأسبوع
df['Day_of_Week'] = df['Date_Cleaned'].dt.day_name()

# 3. حساب عدد الجرائم لكل يوم وترتيبها أيام الأسبوع منطقياً
days_order = ['Saturday', 'Sunday','Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
weekly_crimes = df['Day_of_Week'].value_counts().reindex(days_order).reset_index()
weekly_crimes.columns = ['Day of Week', 'Crime Count']

# --- رسم بياني خطي تفاعلي (Line Chart) يوضح الحركة عبر الأيام ---
fig5= px.line(weekly_crimes, x='Day of Week', y='Crime Count', text='Crime Count',
                     title='Crime Trend Across Days of the Week',
                     labels={'Day of Week': 'Day', 'Crime Count': 'Number of Crimes'},
                     markers=True)
fig5.update_traces(textposition="top center")
fig5.show()

In [ ]:
### Bonus ###
df['Month'] = pd.to_datetime(df['DATE OCC']).dt.month

month_counts = df.groupby('Month').size().reset_index(name='Count')

fig6 = px.line(month_counts,x='Month',y='Count',title='Crimes by Month',markers=True)
fig6.show()

# 2- Night Crime Geography

In [ ]:
# تصفية البيانات للفترة الليلية (من 10 مساءً إلى 3:59 صباحاً)
night=df[(df['Hour']>=22) | (df['Hour']<=3)]
# عدد الجرائم لكل منطقة
# اعلي 10 مناطق
night_counts=(night.groupby('AREA NAME').size().reset_index(name='Count').sort_values('Count',ascending=False).head(10))
print(f'The area with the most night crimes is: {night_area}')
fig2=px.bar(night_counts.sort_values('Count'),x='Count',y='AREA NAME',title='Top 10 Areas-Night Crimes',labels={'AREA NAME':'Area','Count':'Number of Crimes'})
fig2.show()

The area with the most night crimes is: Central

In [ ]:
### Bonus ###
# حساب أعلى 5 مناطق تكررت فيها الجرائم في البيانات كاملة
top_areas = df['AREA NAME'].value_counts().head(5).reset_index()
top_areas.columns = ['Area Name', 'Total Crimes']

# --- رسم بياني شريطي تفاعلي عمودي ---
fig7 = px.bar(top_areas, x='Area Name', y='Total Crimes',title='Top 5 Most Dangerous Areas Overall',labels={'Area Name': 'Area', 'Total Crimes': 'Number of Crimes'})
fig7.show()

# 3- Victim Demographics

In [ ]:
# تصفية الأعمار واستبعاد القيم غير المنطقية (0 و 99)
df_age=df[(df['Vict Age']>0) & (df['Vict Age']<99)]
# تحديد حدود الفئات العمرية والأسماء المطلوبة
bins=[0,17,25,34,44,54,64,120]
labels=['0-17','18-25','26-34','35-44','45-54','55-64','65+']
# تقسيم الأعمار وحساب التكرار وترتيبها بالتتابع الصحيح
df_age['Age Group']=pd.cut(df_age['Vict Age'],bins=bins,labels=labels)
victim_ages=df_age['Age Group'].value_counts().reindex(labels)
# --- الرسم البياني التفاعلي ---
fig3=px.bar(victim_ages,x=victim_ages.index,y=victim_ages.values,title='Victim Age Distribution',labels={'x':'Age Group','y':'Number of Victims'})
fig3.show()

/tmp/ipykernel_3686/3430746115.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

# 4- Anomaly Detection

In [ ]:
# سنستخدم العمود الأصلي كامل 'Vict Age' لرصد الشذوذ بالرسم البياني
# حساب عدد القيم الشاذة إحصائياً بالبايثون (طريقة IQR)
q1=df['Vict Age'].quantile(0.25)
q3=df['Vict Age'].quantile(0.75)
iqr=q3-q1
lower=q1-1.5*iqr
upper=q3+1.5*iqr
outliers=df[(df['Vict Age']<lower) | (df['Vict Age']>upper)]
print(f'The number of outliers is: {len(outliers)}')
print(f'the lower age is: {lower}')
print(f'the upper age is: {upper}')
# --- الرسم البياني التفاعلي (Box Plot) ---
fig4=px.box(df[df['Vict Age']>0],y='Vict Age',title='Outliers in Victim Age')
fig4.show()

The number of outliers is: 0
the lower age is: -67.5
the upper age is: 112.5

In [ ]:
### Bonus ###
fig8=px.histogram(df[df['Vict Age']>0],x='Vict Age',nbins=30,title='Victim Age Distribution')
fig8.show()

In [ ]:
### Bonus ###
top_crimes = df['Crm Cd Desc'].value_counts().head(10).reset_index()
top_crimes.columns = ['Crime Type', 'Count']

fig9 = px.bar(top_crimes.sort_values('Count'),x='Count',y='Crime Type',orientation='h',title='Top 10 Most Common Crimes')
fig9.show()

In [ ]:
### Bonus ###
# تصفية البيانات لاستبعاد القيم غير المعروفة أو غير المحددة في الجنس
filtered_sex_df = df[df['Vict Sex'].isin(['M', 'F'])]

# حساب أعداد الجرائم لكل جنس
sex_counts = filtered_sex_df['Vict Sex'].value_counts().reset_index()
sex_counts.columns = ['Victim Sex', 'Crime Count']

# تغيير الحروف لأسماء واضحة في الرسم
sex_counts['Victim Sex'] = sex_counts['Victim Sex'].map({'M': 'Male', 'F': 'Female'})

# --- رسم بياني دائري تفاعلي (Pie Chart) ---
fig10= px.pie(sex_counts, values='Crime Count', names='Victim Sex',title='Percentage of Crimes by Victim Sex',hole=0.4)
fig10.show()